name: sc test

on:
  workflow_dispatch: # manually
  push: # push
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/nikolaai/toolbox:latest
        
        steps:
          - name: code checkout
            uses: actions/checkout@v2

          - name: get super_secret
            run: |
              echo "${SUPER_SECRET}" | base64 > super_secret.txt
              cat super_secret.txt
            shell: bash
            env:
              SUPER_SECRET: ${{ secrets.SUPER_SECRET }}

          - name: get super_secret2
            run: |
              cat super_secret.txt | base64 -d
            shell: bash