name: sc test

on:
  workflow_dispatch: # manually

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/nikolaai/toolbox:latest
        
        steps:
          - name: code checkout
            uses: actions/checkout@v2

          - name: get super_secret
            run: |
              echo ${{ secrets.SUPER_SECRET }}